package modelDatabase;
// Generated 11/04/2013 09:30:34 by Hibernate Tools 3.2.1.GA



/**
 * Academico generated by hbm2java
 */
public class Academico  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private String telefone;
     private Integer cursoId;

    public Academico() {
    }

    public Academico(String nome, String telefone, Integer cursoId) {
       this.nome = nome;
       this.telefone = telefone;
       this.cursoId = cursoId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public Integer getCursoId() {
        return this.cursoId;
    }
    
    public void setCursoId(Integer cursoId) {
        this.cursoId = cursoId;
    }




}


