package modelDatabase;
// Generated 11/04/2013 09:30:34 by Hibernate Tools 3.2.1.GA



/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private Integer id;
     private String nomeCurso;

    public Curso() {
    }

    public Curso(String nomeCurso) {
       this.nomeCurso = nomeCurso;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNomeCurso() {
        return this.nomeCurso;
    }
    
    public void setNomeCurso(String nomeCurso) {
        this.nomeCurso = nomeCurso;
    }

    @Override
    public String toString() {
        return nomeCurso;
    }




}


