package modelDatabase;
// Generated 11/04/2013 09:30:34 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Salas generated by hbm2java
 */
public class Salas  implements java.io.Serializable {


     private Integer id;
     private String numeroSala;
     private Boolean status;
     private Date horarioUso;

    public Salas() {
    }

    public Salas(String numeroSala, Boolean status, Date horarioUso) {
       this.numeroSala = numeroSala;
       this.status = status;
       this.horarioUso = horarioUso;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNumeroSala() {
        return this.numeroSala;
    }
    
    public void setNumeroSala(String numeroSala) {
        this.numeroSala = numeroSala;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Date getHorarioUso() {
        return this.horarioUso;
    }
    
    public void setHorarioUso(Date horarioUso) {
        this.horarioUso = horarioUso;
    }




}


